# Generated by Django 5.0.3 on 2024-03-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0002_remove_employee_user_employee_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager',
            new_name='admin',
        ),
    ]
