# Generated by Django 5.0.3 on 2024-03-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0003_customuser_is_admin_customuser_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='role',
        ),
    ]
