# Generated by Django 5.0.3 on 2024-03-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0005_remove_customuser_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
